### ISSUE TITLE
Collaboration with others

### ISSUE THREAD

**Issue by DonaldTsang** [lzane/Fingers-Detection-using-OpenCV-and-Python#11]
See https://www.youtube.com/watch?v=DQ8orIurGxw and https://github.com/carykh/jumpcutter
The original author did not integrate the solution of having gestures, hope that you can improve his software and make it happen.
Thanks

**Comment by lzane** [comment]
Sorry, currently I am quite busy on my work.
any people would like to help this are welcome.

**Comment by DonaldTsang** [comment]
@lzane apologies for busying you at work, if you have time in the holidays it would be great to help out as well.
