### ISSUE TITLE
An error occurred after pressing'b'.

### ISSUE THREAD

**Issue by qq1065163616** [lzane/Fingers-Detection-using-OpenCV-and-Python#12]
line 96, in <module>
    _,contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by lzane** [comment]
Please check https://github.com/lzane/Fingers-Detection-using-OpenCV-and-Python/issues/7#issuecomment-509925971

I will update the README later
