### ISSUE TITLE
More than 3 has been identified as 2

### ISSUE THREAD

**Issue by FUZIRONG** [lzane/Fingers-Detection-using-OpenCV-and-Python#13]
After running the program, the effect is not good. The background is solid, but it seems that there is a lot of white noise in the subtracted background binary image, only 1 and 2 are recognized, and 3 or more has been identified as 2

**Comment by lzane** [comment]
It should recognize 3 as well.
Have you try to change the thresholds? plz post some images or I can't help you figure out what's wrong.
