### ISSUE TITLE
将waitkey中的按b提到前面为什么选中的背景是整个矩形框

### ISSUE THREAD

**Issue by 1606701** [lzane/Fingers-Detection-using-OpenCV-and-Python#14]
我想实现不用按键而是间隔时间捕捉图片分析手势内容，像你的恐龙游戏一样

**Comment by lzane** [comment]
你好，看不懂你说的问题，请描述清楚一点。

玩恐龙游戏就是用这份代码来实现的，除了你要自己打开#8
运行过程是不用按键的。

**Comment by 1606701** [comment]
emmm，就是我运行前需要按b才会执行bgModel = cv2.createBackgroundSubtractorMOG2(0, bgSubThreshold)做背景处理，每次都需要按b然后按r再按b才有完整的手的轮廓

**Comment by lzane** [comment]
是的，如果你背景是固定的，你应该可以通过调参实现按一次b就可以得到完整的手轮廓。
如果你的背景是运动的，那这个方法不适合你，需要研究下其他方案。
