### ISSUE TITLE
如果空格键之后，键盘会被占用啊

### ISSUE THREAD

**Issue by YHR98** [lzane/Fingers-Detection-using-OpenCV-and-Python#18]

**Comment by lzane** [comment]
请详细描述问题，不然没法帮到你

**Comment by YHR98** [comment]
我的意思是，运行程序后，有很多误判率，我的键盘会一直被占用，还有手势识别是不是只能识别一种手势？

**Comment by YHR98** [comment]
你好，你的第96行代码有问题，你的下划线表示什么意思啊，删掉下划线程序正常运行。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LZANE | 李泽帆"<notifications@github.com&gt;; 
发送时间: 2020年3月14日(星期六) 下午3:50
收件人: "lzane/Fingers-Detection-using-OpenCV-and-Python"<Fingers-Detection-using-OpenCV-and-Python@noreply.github.com&gt;; 
抄送: "…‖～～"<360157112@QQ.COM&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lzane/Fingers-Detection-using-OpenCV-and-Python] 如果空格键之后，键盘会被占用啊 (#18)





 
请详细描述问题，不然没法帮到你

**Comment by YHR98** [comment]
你好，你的第96行代码有问题，你的下划线表示什么意思啊，删掉下划线后程序正常运行。

**Comment by lzane** [comment]
请阅读README中的
```
for people using opencv4, please change line 96 in the new.py to contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE) according to the opencv api change.
```

大概率是openCV版本问题
