### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by shakram02** [lzane/Fingers-Detection-using-OpenCV-and-Python#4]
This line
```python
 bgModel = cv2.BackgroundSubtractorMOG2(0, bgSubThreshold)
```
should be

```python
cv2.createBackgroundSubtractorMOG2(0, bgSubThreshold)
```

and 

```python
contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
```
should be 
```python
x, contours, y = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
```

**Comment by lzane** [comment]
Thank you for pointing this out. But I don't have time to make modify the code.

Could you please change the code and then create a pull request? 
Thx~

**Comment by shakram02** [comment]
Done, I edited it in the browser, couldn't re-check the code. but it's working on my machine

uw

**Comment by lzane** [comment]
Actually I just find out that this "Deprecated code" problem has already been solved by other contributors. You can find it in branch `lzane:py3_opencv3`.

I have the following announcement in the very beginning of the README
> for people using python3 and opencv3, please check out the lzane:py3_opencv3 branch.

I leave the original code just for people who use python2 and OpenCV2.

I closed your issue and pull request. Anyway, thanks for your contribution.

**Comment by shakram02** [comment]
I suggest that you swap the python3 branch to be master. Thanks a lot :+1:

**Comment by lzane** [comment]
@shakram02 I agree with you, done.
