### ISSUE TITLE
dinosaur appscript source?

### ISSUE THREAD

**Issue by mauckc** [lzane/Fingers-Detection-using-OpenCV-and-Python#8]
Where is this dinosaur appscript control file??

**Comment by lzane** [comment]
It only triggle a blank key at certain time.

see

https://github.com/lzane/Fingers-Detection-using-OpenCV-and-Python/blob/0b57a6dabb2da5ba1c9e9b3e2ce5aa89919e662b/new.py#L117

you need to uncomment this line.

**Comment by lzane** [comment]
https://github.com/lzane/Fingers-Detection-using-OpenCV-and-Python/blob/0b57a6dabb2da5ba1c9e9b3e2ce5aa89919e662b/new.py#L117
