### ISSUE TITLE
Small change to calculateFingers

### ISSUE THREAD

**Issue by aisosalo** [lzane/Fingers-Detection-using-OpenCV-and-Python#9]
How about moving the plotting of the circle outside the `def`and then using the new `cavity_pts` output to plot the points?

PS. What kind of license you have for your software? Can I use a modified version of this function in a non-commercial research purpose? How do you want yourself to be mentioned if you allow the usage?

```
def calculateFingers(max_c):
    """
    https://github.com/lzane/Fingers-Detection-using-OpenCV-and-Python/blob/master/new.py#L39-L60
    """
    hull = cv2.convexHull(max_c, returnPoints=False)
    if len(hull) > 3:
        try:
            defects = cv2.convexityDefects(max_c, hull)
        except Exception:
            defects = None
        
        counter = 0
        if defects is not None:
            cavity_pts = []
            for i in range(defects.shape[0]):  # calculate the angle
                s, e, f, d = defects[i][0]
                start = tuple(max_c[s][0])
                end = tuple(max_c[e][0])
                far = tuple(max_c[f][0])
                a = math.sqrt((end[0] - start[0]) ** 2 + (end[1] - start[1]) ** 2)
                b = math.sqrt((far[0] - start[0]) ** 2 + (far[1] - start[1]) ** 2)
                c = math.sqrt((end[0] - far[0]) ** 2 + (end[1] - far[1]) ** 2)
                angle = math.acos((b ** 2 + c ** 2 - a ** 2) / (2 * b * c))  # cosine theorem
                if angle <= math.pi / 2:  # angle less than 90 degree, treat as fingers
                    counter += 1
                    cavity_pts.append(far)
            return counter, cavity_pts
    return 0, []
```

**Comment by lzane** [comment]
looks great. Please pr if you've already test it out.

For the license, of course you can use it for non-commercial research purpose. 
Actually, you can use it in any way you like. I will add a MIT license to this repo.

**Comment by lzane** [comment]
here 991a551

**Comment by aisosalo** [comment]
> looks great. Please pr if you've already test it out.

It works on my application.
 
> For the license, of course you can use it for non-commercial research purpose.
> Actually, you can use it in any way you like. I will add a MIT license to this repo.

I have seen this

```
s, e, f, d = defects[i][0]
start = tuple(max_c[s][0])
end = tuple(max_c[e][0])
far = tuple(max_c[f][0])
```
also in some other tutorial. So this is now a combination of scripts from many authors. How does that go according to the licence, if published?

**Comment by lzane** [comment]
> So this is now a combination of script from many authors.

Yes

> How does that go according to the license, if published?

I write this script based on the idea from this [repo](https://github.com/mahaveerverma/hand-gesture-recognition-opencv), and it's under MIT license.
